[files]
ignore-hidden = false
[default]
    "\\bBig Sur\\b",
    '(firstItem|secondItem|id|destination|headerView)="[0-9A-Za-z]+-[0-9A-Za-z]+-[0-9A-Za-z]+"',
    "ba!",
]

"abitrate" = "abitrate"
[default.extend-identifiers]
"caf" = "caf"
"reloadSavedIINAfilters" = "reloadSavedIINAfilters"
"tak" = "tak"